runMode: debug
addr: :9012
jwt:
  sign: hdfhdsiwurq12
  issue: sai
  ttl: 600
  name: jwt_token
db:
  name: user
  host: 127.0.0.1:3316
  username: root
  password: 111111
  charset: utf8mb4
  log: 0
redis:
  host: 127.0.0.1
  port: 6389
  auth: 
  db: 5
  MaxActive: 32
  MaxIdle: 8
  IdleTimeout: 5
log:
  level: debug
  file_format: "%Y%m%d"
  max_save_days: 30
  file_type: one #one, level